# Generated by Django 4.0.4 on 2022-05-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SetimentAnalysis',
            new_name='SentimentAnalysis',
        ),
    ]
